language: go

os:
  - linux
  - osx

go:
  - "1.12"

services:
  - docker

git:
  depth: 3

go_import_path: logancloud/logan-app-operator

before_install:
  - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"

install:
  - go get -u github.com/golang/dep/cmd/dep

script:
  - make build
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" ] && [ "${TRAVIS_BRANCH}" = "master" ]; then
    make push;
    fi