apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: javaboots.app.logancloud.com
spec:
  group: app.logancloud.com
  names:
    kind: JavaBoot
    listKind: JavaBootList
    plural: javaboots
    singular: javaboot
    shortNames:
      - java
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            env:
              items:
                properties:
                  name:
                    type: string
                  value:
                    type: string
              type: array
            health:
              type: string
            image:
              type: string
            nodeSelector:
#              additionalProperties:
#                type: string
              type: object
            port:
              format: int32
              type: integer
            replicas:
              format: int32
              type: integer
            resources:
              type: object
            subDomain:
              type: string
            version:
              type: string
            command:
              type: array
              items:
                type: string
          required:
          - image
          - version
          type: object
        status:
          type: object
  version: v1
  versions:
  - name: v1
    served: true
    storage: true
